// Re-export from sub-modules
export { executeReasoningChain, buildReasoningContext } from './dialogue-reasoning'
export { startDialogueStream, cancelDialogueStream, handleApprovalResponse } from './dialogue-stream'
export { autoPolish, polishText } from './client-polish'
export { summarizeChapter } from './client-summary'
export { generateContinuation } from './continuation'
export { refineSummary } from './refine-summary'
export { estimateTokens, estimateMessagesTokens, createBudget, truncateToTokenBudget } from './token-counter'
export { compressHistory, compressConversationMessages, compressForStorage, compressConversationForStorage } from './context-compressor'
export { getCompressionStrategy } from './compression-strategy'
export { scoreChunk, scoreToImportance, scoreMessages, filterByImportance } from './importance-scorer'
export type { ScoredChunk, ChunkImportance } from './importance-scorer'
export { chunkText, prioritizeChunks } from './chunking'
export type { Chunk, ChunkingOptions } from './chunking'
export { summarizeWithLLM } from './summary-memory'
export type { SummaryEntry } from './summary-memory'
export { compressHistoryWithSummary } from './history-compressor'
export { callWithTools } from './call-with-tools'
export type { CallWithToolsParams, CallWithToolsResult } from './call-with-tools'
