// Agent module barrel file
export { WriterAgentController } from './wac'
export { AgentRuntime, getAgentRuntime, disposeAgentRuntime } from './runtime'
export { classifyIntent } from './intent-classifier'
export { routeRequest } from './task-router'
export type { RouteContext, RouteResult } from './task-router'
export { executeAnalysisPipeline } from './analysis-pipeline'
export type { AnalysisPipelineParams } from './analysis-pipeline'
export { executeCritic } from './critic'
export { executePlanner } from './planner'
export { executeWriter } from './writer'
export { executeEditor } from './editor'
export { callLLM, callLLMSync } from './base-agent'
export { WritingStateMachine, createWritingStateMachine } from './state-machine'
export { selectRewriteStrategy } from './rewrite-strategy'
export { trackScoreTrend, shouldStopRewrite } from './score-trend'
export type { ScoreTrend } from './score-trend'
export { executeTaskGraph } from './task-executor'
export { resolveDependencyLayers } from './task-resolver'
export type { TaskExecutionResult } from './task-executor'
